kind: Service
apiVersion: v1
metadata:
  name: reddit
  labels:
    app: reddit
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31704
    protocol: TCP
    name: http
  selector:
    app: reddit
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: reddit
spec:
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#podspec-v1-core
    spec:
      containers:
      - name: web
        image: reddit_web
        imagePullPolicy: IfNotPresent
        command:
          - /app/start-web.sh
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: reddit.settings.prod
          - name: CELERY_HOST
            value: localhost
          - name: REDIS_HOST
            value: localhost
          - name: DEBUG
            value: 'True'
          - name: DB_NAME
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: password
          - name: DB_HOST
            value: database
          - name: DB_PORT
            value: '5432'
      - name: worker
        image: reddit_web
        imagePullPolicy: IfNotPresent
        command:
          - /app/start-worker.sh
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: reddit.settings.prod
          - name: CELERY_HOST
            value: localhost
          - name: REDIS_HOST
            value: localhost
          - name: DEBUG
            value: 'True'
          - name: DB_NAME
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: password
          - name: DB_HOST
            value: database
          - name: DB_PORT
            value: '5432'
      - name: rabbit
        image: rabbitmq
      - name: redis
        image: redis
