version: '3'

services:
    worker:
        image: localhost:5000/reddit
        environment:
            DEBUG: 'True'
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASSWORD: password
            DB_HOST: database
            DB_PORT: 5432
            CELERY_HOST: rabbit
            REDIS_HOST: redis
            DJANGO_SETTINGS_MODULE: reddit.settings
    web:
        image: localhost:5000/reddit
        entrypoint: /app/start-web.sh
        environment:
            DEBUG: 'True'
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASSWORD: password
            DB_HOST: database
            DB_PORT: 5432
            CELERY_HOST: rabbit
            REDIS_HOST: redis
            DJANGO_SETTINGS_MODULE: reddit.settings
