version: '3'

services:
    rabbit:
        image: rabbitmq
    redis:
        image: redis
    worker:
        image: localhost:5000/reddit
        entrypoint: /app/start-worker.sh
        environment:
            - CELERY_HOST=rabbit
            - REDIS_HOST=redis
            - DJANGO_SETTINGS_MODULE=reddit.settings.prod
            # Pass-through
            - DEBUG
            - REDDIT_DB_NAME=reddit
            - REDDIT_DB_PORT=5432
            - REDDIT_DB_USER
            - REDDIT_DB_PASSWORD
            - REDDIT_DB_HOST
    web:
        image: localhost:5000/reddit
        entrypoint: /app/start-web.sh
        ports:
            - 8000:8000
        environment:
            - DEBUG=False
            - CELERY_HOST=rabbit
            - REDIS_HOST=redis
            - DJANGO_SETTINGS_MODULE=reddit.settings.prod
            # Pass-through
            - REDDIT_DB_NAME=reddit
            - REDDIT_DB_PORT=5432
            - REDDIT_DB_USER
            - REDDIT_DB_PASSWORD
            - REDDIT_DB_HOST
