version: '3'

services:
    redis:
        image: redis
    worker:
        image: localhost:5000/reddit
        entrypoint: /app/start-worker.sh
        environment:
            - DJANGO_SETTINGS_MODULE=reddit.settings.prod
            - CELERY_HOST=redis
            - REDIS_HOST=redis
            # Postgres
            - PGDATABASE=reddit
            - PGUSER=$REDDIT_DB_USER
            - PGPASSWORD=$REDDIT_DB_PASSWORD
            - PGHOST=$DOCKERHOST
            - PGPORT=5432
            # Pass-through
            - DJANGO_SECRET_KEY
            - REDDIT_RAVEN_DSN
    web:
        image: localhost:5000/reddit
        entrypoint: /app/start-web.sh
        ports:
            - 8002:8002
        environment:
            - DJANGO_SETTINGS_MODULE=reddit.settings.prod
            - CELERY_HOST=redis
            - REDIS_HOST=redis
            # Postgres
            - PGDATABASE=reddit
            - PGUSER=$REDDIT_DB_USER
            - PGPASSWORD=$REDDIT_DB_PASSWORD
            - PGHOST=$DOCKERHOST
            - PGPORT=5432
            # Pass-through
            - DJANGO_SECRET_KEY
            - REDDIT_RAVEN_DSN
