version: '2'

services:
    database:
        image: postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    rabbit:
        image: rabbitmq
    redis:
        image: redis
    worker:
        entrypoint: /app/start-worker.sh
        build:
            context: .
            dockerfile: dockerfile.worker
        volumes:
            - ./app:/app
        links:
            - database
            - rabbit
            - redis
        environment:
            DEBUG: 'True'
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASSWORD: password
            DB_HOST: database
            DB_PORT: 5432
            CELERY_HOST: rabbit
            DJANGO_SETTINGS_MODULE: app.settings
    web:
        entrypoint: /app/start-web.sh
        build:
            context: .
            dockerfile: dockerfile.web
        ports:
            - 8000:8000
        volumes:
          - ./app:/app
        links:
            - database
            - rabbit
            - redis
            - worker
        environment:
            DEBUG: 'True'
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASSWORD: password
            DB_HOST: database
            DB_PORT: 5432
            CELERY_HOST: rabbit
            DJANGO_SETTINGS_MODULE: app.settings
