# Generated by Django 2.0.4 on 2018-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='loading',
            field=models.BooleanField(default=False),
        ),
    ]
